server:
   port: ${PORT:9080}
application:
   name: ^project.artifactId^
   description: ^project.name^
   version: ^project.version^
eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://${DISCOVERY_HOST:localhost}:${DISCOVERY_PORT:8761}/eureka/}

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes: # these are samples
      - id: micro-service
        uri: lb://micro-service
        predicates:
        - Path=/service/**
        filters:
        - RewritePath=/service/(?<path>.*), /$\{path}
 
      